### ISSUE TITLE
Ability to remove params

### ISSUE THREAD

**Issue by willrax** [jamesplease/query-history#17]
In some cases, it's required to remove a parameter but retain any others that might be present in the URL. eg: Using a qp to hide and show a global modal. If there are other parts of the app using qp's to represent filters and then the user opens a modal, we would want to be able to close the modal and retain the filters.

**Comment by jamesplease** [comment]
Thanks for the issue! I need to add this to the docs.

This depends on the option that you pass to `queryString`. If you're using the default settings (which I think most people are doing), then one way is to pass the value as `undefined` when passing params.

```js
// Add "sandwiches" to the query params:
queryHistory.updateQuery({
  sandwiches: true
});

// Remove "sandwiches" from the query params:
queryHistory.updateQuery({
  sandwiches: undefined
});
```

Let me know if that works for you!
